Complete array exercises
koremori/study pull request #1
Opened 2021-11-17 21:19 UTC by koremori

2021-11-18 15:10 UTC, moklidia requested changes

2021-11-18 15:10 UTC, moklidia commented on test/exercise/arrays/solution.rb
> +        array.map { |num| num.positive? ? max_value(array) : num }
В этой реализации получается, что на каждом элементе ты ищешь максимальный элемент массива заново - это много лишних действий.

2021-11-18 18:28 UTC, koremori commented on test/exercise/arrays/solution.rb
> +        array.map { |num| num.positive? ? max_value(array) : num }
Действительно. Благодарю!

2021-11-19 11:24 UTC, moklidia approved these changes

2021-11-19 11:32 UTC, merged